# Generated by Django 5.0.6 on 2024-06-25 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Danio',
            fields=[
                ('id_dan', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_dan', models.FileField(blank=True, null=True, upload_to='danio')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_dir', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad_dir', models.CharField(max_length=255)),
                ('barrio_dir', models.CharField(max_length=255)),
                ('calle_dir', models.CharField(max_length=255)),
                ('numero_dir', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ins', models.CharField(max_length=255)),
                ('valor_ins', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ser', models.CharField(max_length=255)),
                ('descripcion_ser', models.TextField()),
                ('precio_ser', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tall', models.CharField(max_length=255)),
                ('descripcion_tall', models.TextField()),
                ('logo_tall', models.FileField(blank=True, null=True, upload_to='Taller')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usr', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('MECANICO', 'Mecánico')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=255)),
                ('apellido_cli', models.CharField(max_length=255)),
                ('ci_cli', models.CharField(max_length=10, unique=True)),
                ('telefono_cli', models.CharField(max_length=20)),
                ('email_cli', models.EmailField(max_length=254, unique=True)),
                ('dir_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ord', models.DateField()),
                ('numero_ord', models.IntegerField()),
                ('observaciones_ord', models.TextField()),
                ('estado_ord', models.IntegerField()),
                ('danios_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.danio')),
                ('inspeccion_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.inspeccion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenRepuesto',
            fields=[
                ('id_rep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rep', models.CharField(max_length=255)),
                ('descripcion_rep', models.TextField()),
                ('precio_rep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_rep', models.IntegerField()),
                ('subtotal_rep', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_ord_ser', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.orden')),
                ('servicio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_veh', models.AutoField(primary_key=True, serialize=False)),
                ('marca_veh', models.CharField(max_length=255)),
                ('modelo_veh', models.CharField(max_length=255)),
                ('placa_veh', models.CharField(max_length=20, unique=True)),
                ('anio_veh', models.IntegerField()),
                ('km_veh', models.IntegerField()),
                ('chasis_veh', models.CharField(max_length=255)),
                ('color_veh', models.CharField(max_length=255)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='vehiculo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.vehiculo'),
        ),
    ]
