# Generated by Django 5.0.6 on 2024-07-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='danios_id',
        ),
    ]
